ServiceHost/Areas/Admin/Pages/Accounts/Account/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Application;
using AccountManagement.Application.Contracts.Account;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Admin.Pages.Accounts.Account
{
    public class IndexModel : PageModel
    {
        private readonly IAccountApplication _accountApplication;
        private readonly IRoleApplication _roleApplication;

        public IndexModel(IAccountApplication accountApplication, IRoleApplication roleApplication)
        {
            _accountApplication = accountApplication;
            _roleApplication = roleApplication;
        }

        public List<AccountViewModel> Accounts;
        public AccountSearchModel SearchModel;
        public SelectList Roles;

        public void OnGet(AccountSearchModel searchModel)
        {
            Accounts = _accountApplication.Search(searchModel);
            Roles=new SelectList(_roleApplication.GetRoles(),"Id","Name");
        }

        public IActionResult OnGetEdit(long id)
        {
            var editAccount = _accountApplication.GetDetails(id);
            editAccount.Roles = _roleApplication.GetRoles();
            return Partial("Edit", editAccount);
        }

        public IActionResult OnGetCreate(long id)
        {
            var createAccount=new CreateAccount();
            createAccount.Roles = _roleApplication.GetRoles();
            return Partial("Create",createAccount);
        }

        public IActionResult OnPostEdit(EditAccount command)
        {
            var result = new OperationResult();
            if (ModelState.IsValid)
            {
                result=_accountApplication.Edit(command);
            }
            return new JsonResult(result);
        }

        public IActionResult OnPostCreate(CreateAccount command)
        {
            var result = new OperationResult();
            if (ModelState.IsValid)
            {
                result = _accountApplication.Register(command);
            }
            return new JsonResult(result);
        }

        public IActionResult OnGetChangePassword(long id)
        {
            var changePassword = new ChangePassword(){Id = id};
            return Partial("ChangePassword", changePassword);
        }

        public IActionResult OnPostChangePassword(ChangePassword command)
        {
            var result = new OperationResult();
            if (ModelState.IsValid)
            {
                result = _accountApplication.ChangePassword(command);
            }
            return new JsonResult(result);
        }

    }
}

ServiceHost/Areas/Admin/Pages/Accounts/Role/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Admin.Pages.Accounts.Role
{
    public class CreateModel : PageModel
    {
        private readonly IRoleApplication _roleApplication;

        public CreateModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public CreateRole Command;

        public void OnGet()
        {
            Command=new CreateRole();
        }

        public IActionResult OnPost(CreateRole command)
        {
            _roleApplication.Create(command);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Admin/Pages/Accounts/Role/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Admin.Pages.Accounts.Role
{
    public class EditModel : PageModel
    {
        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _permissionExposer;

        public EditModel(IRoleApplication roleApplication, IEnumerable<IPermissionExposer> permissionExposer)
        {
            _roleApplication = roleApplication;
            _permissionExposer = permissionExposer;
        }

        [BindProperty]
        public EditRole Role { get; set; }

        public List<SelectListItem> Permissions;

        public void OnGet(long id)
        {
            Role = _roleApplication.GetDetails(id);
            Permissions=new List<SelectListItem>();

            foreach (var exposer in _permissionExposer)
            {
                var exposedPermission = exposer.Expose();
                foreach (var (key, value) in exposedPermission)
                {
                    var group = new SelectListGroup()
                    {
                        Name = key
                    };
                    foreach (var permission in value)
                    {
                        var item = new SelectListItem(permission.Name, permission.Code.ToString())
                        {
                            Group = group
                        };

                        if (Role.MappedPermissions.Any(x => x.Code == permission.Code))
                        {
                            item.Selected = true;
                        }

                        Permissions.Add(item);
                    }
                }
            }
        }

        public IActionResult OnPost(/*EditRole command*/)
        {
            _roleApplication.Edit(Role);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Admin/Pages/Accounts/Role/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Application;
using AccountManagement.Application.Contracts.Account;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Admin.Pages.Accounts.Role
{
    public class IndexModel : PageModel
    {
        private readonly IRoleApplication _roleApplication;

        public IndexModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public List<RoleViewModel> Roles;
        public void OnGet()
        {
            Roles = _roleApplication.GetRoles();
        }

        public IActionResult OnGetEdit(long id)
        {
            var editAccount = _roleApplication.GetDetails(id);
            return Partial("Edit", editAccount);
        }

        public IActionResult OnGetCreate(long id)
        {
            var createRole = new CreateRole();
            return Partial("Create", createRole);
        }

        public IActionResult OnPostEdit(EditRole command)
        {
            var result = new OperationResult();
            if (ModelState.IsValid)
            {
                result = _roleApplication.Edit(command);
            }
            return new JsonResult(result);
        }

        public IActionResult OnPostCreate(CreateRole command)
        {
            var result = new OperationResult();
            if (ModelState.IsValid)
            {
                result = _roleApplication.Create(command);
            }
            return new JsonResult(result);
        }
    }
}

ServiceHost/Areas/Admin/Pages/Shop/Product/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Application;
using _0_Framework.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.ProductAgg;
using ShopManagement.Application.Contracts.ProductCategory;
using ShopManagement.Configuration.Permissions;

namespace ServiceHost.Areas.Admin.Pages.Shop.Product
{
    public class IndexModel : PageModel
    {
        private readonly IProductApplication _productApplication;
        private readonly IProductCategoryApplication _productCategoryApplication;

        public IndexModel(IProductApplication productApplication, IProductCategoryApplication productCategoryApplication)
        {
            _productApplication = productApplication;
            _productCategoryApplication = productCategoryApplication;
        }

        public List<ProductViewModel> Products;
        public ProductSearchModel SearchModel;
        public SelectList Categories;

        [NeedsPermission(ShopPermissions.ListProducts)]
        public void OnGet(ProductSearchModel searchModel)
        {
            Products = _productApplication.Search(searchModel);
            Categories=new SelectList(_productCategoryApplication.GetCategories(),"Id","Name");
        }

        [NeedsPermission(ShopPermissions.EditProduct)]
        public IActionResult OnGetEdit(long id)
        {
            var product = _productApplication.GetDetails(id);
            product.Categories = _productCategoryApplication.GetCategories();
            return Partial("Edit", product);
        }

        [NeedsPermission(ShopPermissions.EditProduct)]
        public IActionResult OnPostEdit(EditProduct command)
        {
            var result = new OperationResult();
            if (ModelState.IsValid)
            {
                result = _productApplication.Edit(command);
            }
            return new JsonResult(result);
        }

        [NeedsPermission(ShopPermissions.CreateProduct)]
        public IActionResult OnGetCreate()
        {
            var product = new CreateProduct();
            product.Categories = _productCategoryApplication.GetCategories();
            return Partial("Create",product );
        }

        [NeedsPermission(ShopPermissions.CreateProduct)]
        public IActionResult OnPostCreate(CreateProduct command)
        {
            var result = new OperationResult();
            if (ModelState.IsValid)
            {
                result = _productApplication.Create(command);
            }
            return new JsonResult(result);
        }

    }
}

ServiceHost/Areas/Admin/Pages/Shop/ProductCategory/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Application;
using _0_Framework.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.ProductCategory;
using ShopManagement.Configuration.Permissions;

namespace ServiceHost.Areas.Admin.Pages.Shop.ProductCategory
{
    public class IndexModel : PageModel
    {
        private readonly IProductCategoryApplication _productCategoryApplication;

        public IndexModel(IProductCategoryApplication productCategoryApplication)
        {
            _productCategoryApplication = productCategoryApplication;
        }


        public ProductCategorySearchModel SearchModel;

        public List<ProductCategoryViewModel> ProductCategories { get; set; }

        [NeedsPermission(ShopPermissions.ListProductCategories)]
        public void OnGet(ProductCategorySearchModel searchModel)
        {
            ProductCategories = _productCategoryApplication.Search(searchModel);
        }

        [NeedsPermission(ShopPermissions.CreateProductCategory)]
        public IActionResult OnGetCreate()
        {
            return Partial("Create", new CreateProductCategory());
        }

        [NeedsPermission(ShopPermissions.CreateProductCategory)]
        public IActionResult OnPostCreate(CreateProductCategory command)
        {
            var result = new OperationResult();
            if (ModelState.IsValid)
            {
                result=_productCategoryApplication.Create(command);
            }
            return new JsonResult(result);
        }

        [NeedsPermission(ShopPermissions.EditProductCategory)]
        public IActionResult OnGetEdit(long id)
        {
            return Partial("Edit", _productCategoryApplication.GetDetails(id));
        }

        [NeedsPermission(ShopPermissions.EditProductCategory)]
        public IActionResult OnPostEdit(EditProductCategory command)
        {
            var result=new OperationResult();
            if (ModelState.IsValid)
            {
                result = _productCategoryApplication.Edit(command);
            }
            return new JsonResult(result);
        }
    }
}

ServiceHost/Pages/Account.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Application;
using AccountManagement.Application.Contracts.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class AccountModel : PageModel
    {
        private readonly IAccountApplication _accountApplication;

        public AccountModel(IAccountApplication accountApplication)
        {
            _accountApplication = accountApplication;
        }


        [TempData]
        public string LoginMessage { get; set; }

        [TempData]
        public string RegisterMessage { get; set; }

        [BindProperty]
        public LoginModel LoginModel { get; set; }

        [BindProperty]
        public RegisterAccount RegisterAccount { get; set; }

        public void OnGet()
        {
            LoginModel = new LoginModel();
        }

        public IActionResult OnPostLogin()
        {
            var operationResult = new OperationResult();

            operationResult = _accountApplication.Login(LoginModel);
            if (operationResult.IsSucceeded)
            {
                return RedirectToPage("./Index");
            }

            LoginMessage = operationResult.Message;

            return Page();
        }

        public IActionResult OnPostRegister()
        {
            var operationResult = new OperationResult();

            var createAccount = new CreateAccount()
            {
                Username = RegisterAccount.Username,
                Password = RegisterAccount.Password,
                RoleId = 2,
                Mobile = RegisterAccount.Mobile,
                Fullname = RegisterAccount.Fullname,
            };
            operationResult = _accountApplication.Register(createAccount);
            if (!operationResult.IsSucceeded)
                RegisterMessage = operationResult.Message;


            return Page();
        }

        public IActionResult OnGetLogout()
        {
            _accountApplication.Logout();
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Pages/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Application;
using _01_ShopQuery.Contracts.Product;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using ShopManagement.Application.Contracts.Order;

namespace ServiceHost.Pages
{
    public class CartModel : PageModel
    {
        public List<CartItem> CartItems { get; set; }
        private const string CookieName = "cart-items";

        private readonly IProductQuery _productQuery;

        public CartModel(IProductQuery productQuery)
        {
            _productQuery = productQuery;
        }

        public void OnGet()
        {
            CartItems=new List<CartItem>();
            var cookie = Request.Cookies[CookieName];
            if (cookie!=null)
            {
                CartItems = JsonConvert.DeserializeObject<List<CartItem>>(cookie);
                CartItems.ForEach(x =>
                {
                    var stringPrice = x.Price.Replace("٬", "");
                    var price = double.Parse(stringPrice);
                    x.TotalPrice = (price * x.Count).ToMoney();
                });

                _productQuery.CheckCartItemStatus(CartItems);
            }
            
        }

        public IActionResult OnGetRemoveCartItem(long id)
        {
            var cookie = Request.Cookies[CookieName];
            CartItems = JsonConvert.DeserializeObject<List<CartItem>>(cookie);

            var cartItemToBeRemoved = CartItems.FirstOrDefault(x => x.Id == id);
            if (cartItemToBeRemoved!=null)
            {
                CartItems.Remove(cartItemToBeRemoved);
                Response.Cookies.Delete(CookieName);
                var cookieOptions = new CookieOptions() { Expires = DateTime.Now.AddDays(1) };
                Response.Cookies.Append(CookieName,JsonConvert.SerializeObject(CartItems),cookieOptions);
            }

            return RedirectToPage("Cart");

        }

        public IActionResult OnGetGoToCheckout()
        {
            var cookie = Request.Cookies[CookieName];
            if (cookie!=null)
            {
                CartItems = JsonConvert.DeserializeObject<List<CartItem>>(cookie);
                _productQuery.CheckCartItemStatus(CartItems);
                if (!CartItems.Any(x=>x.IsInStock==false))
                {
                    return RedirectToPage("Checkout");
                }
            }
            CartItems.ForEach(x =>
            {
                var stringPrice = x.Price.Replace("٬", "");
                var price = double.Parse(stringPrice);
                x.TotalPrice = (price * x.Count).ToMoney();
            });
            return RedirectToPage("Cart");
        }
    }
}

ServiceHost/Pages/AccessDenied.cshtml
@page
@model ServiceHost.Pages.AccessDeniedModel
@{
    
}

<div class="alert alert-danger">
    <h1>404 !</h1>
    <h2>متاسفانه شما اجازه دسترسی به این صفحه را ندارید.</h2>
    <a class="btn btn-purple waves-effect waves-light" asp-page="./Index">بازگشت به صفحه اصلی</a>
</div>

ServiceHost/Pages/Account.cshtml
@page
@model ServiceHost.Pages.AccountModel
@{
    ViewData["Title"] = "ورود و ثبت نام";
}


<div class="breadcrumb-area section-space--half">
    <div class="container wide">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-wrapper breadcrumb-bg">
                    <div class="breadcrumb-content">
                        <h2 class="breadcrumb-content__title">ورود - ثبت نام</h2>
                        <ul class="breadcrumb-content__page-map">
                            <li><a asp-page="./Index">صفحه اصلی</a></li>
                            <li class="active">ورود - ثبت نام</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="page-content-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-wrapper">
                    <div class="page-content-wrapper">
                        <div class="row">
                            <div class="col-sm-12 col-md-12 col-xs-12 col-lg-6">
                                @if (Model.LoginMessage != null)
                                {
                                    <div class="alert alert-danger">
                                        <p>@Model.LoginMessage</p>
                                    </div>
                                }
                                <form method="post" asp-page-handler="login">
                                    <div class="login-form">
                                        <h4 class="login-title">ورود</h4>
                                        <div class="row">
                                            <div class="col-md-12 col-12">
                                                <label>نام کاربری</label>
                                                <input asp-for="LoginModel.Username" placeholder="نام کاربری">
                                                <span asp-validation-for="LoginModel.Username" class="error"></span>
                                            </div>
                                            <div class="col-12">
                                                <label>کلمه عبور</label>
                                                <input asp-for="LoginModel.Password" placeholder="کلمه عبور">
                                                <span asp-validation-for="LoginModel.Password" class="error"></span>
                                            </div>
                                            @*<div class="col-sm-6">

                                                    <div class="check-box d-inline-block ml-0 ml-md-2">
                                                        <input type="checkbox" id="remember_me">
                                                        <label for="remember_me">Remember me</label>
                                                    </div>

                                                </div>*@

                                            <div class="col-sm-6 text-left text-sm-right">
                                                <a href="#" class="forget-pass-link">کلمه عبور خود را فراموش کرده اید ؟</a>
                                            </div>

                                            <div class="col-md-12">
                                                <button class="register-button">ورود</button>
                                            </div>

                                        </div>
                                    </div>

                                </form>
                            </div>
                            <div class="col-sm-12 col-md-12 col-lg-6 col-xs-12">
                                @if (Model.RegisterMessage != null)
                                {
                                    <div class="alert alert-danger">
                                        <p>@Model.RegisterMessage</p>
                                    </div>
                                }
                                <form method="post" asp-page-handler="Register">

                                    <div class="login-form">
                                        <h4 class="login-title">ثبت نام</h4>

                                        <div class="row">
                                            <div class="col-md-6 col-12 mb-20">
                                                <label>نام و نام خانوادگی</label>
                                                <input asp-for="RegisterAccount.Fullname" placeholder="نام و نام خانوادگی">
                                                <span asp-validation-for="RegisterAccount.Fullname" class="error"></span>
                                            </div>
                                            <div class="col-md-6 col-12 mb-20">
                                                <label>نام کاربری</label>
                                                <input asp-for="RegisterAccount.Username" placeholder="نام کاربری">
                                                <span asp-validation-for="RegisterAccount.Username" class="error"></span>
                                            </div>
                                            <div class="col-md-12 mb-20">
                                                <label>موبایل</label>
                                                <input asp-for="RegisterAccount.Mobile" placeholder="موبایل">
                                                <span asp-validation-for="RegisterAccount.Mobile" class="error"></span>
                                            </div>
                                            <div class="col-md-6 mb-20">
                                                <label>کلمه عبور</label>
                                                <input asp-for="RegisterAccount.Password" placeholder="کلمه عبور">
                                                <span asp-validation-for="RegisterAccount.Password" class="error"></span>
                                            </div>
                                            <div class="col-md-6 mb-20">
                                                <label>تایید کلمه عبور</label>
                                                <input asp-for="RegisterAccount.ConfirmPassword" placeholder="تایید کلمه عبور">
                                                <span asp-validation-for="RegisterAccount.ConfirmPassword" class="error"></span>
                                            </div>
                                            <div class="col-12">
                                                <button class="register-button mt-0">ثبت نام</button>
                                            </div>
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

ServiceHost/Pages/Cart.cshtml
@page
@model ServiceHost.Pages.CartModel
@{
    ViewData["Title"] = "سبد خرید";
}


<div class="breadcrumb-area section-space--half">
    <div class="container wide">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-wrapper breadcrumb-bg">
                    <div class="breadcrumb-content">
                        <h2 class="breadcrumb-content__title">سبد خرید شما</h2>
                        <ul class="breadcrumb-content__page-map">
                            <li>
                                <a asp-page="/Index">صفحه اصلی</a>
                            </li>
                            <li class="active">سبد خرید</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="page-content-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <!--=======  page wrapper  =======-->
                <div class="page-wrapper">
                    @foreach (var item in Model.CartItems.Where(x => x.IsInStock == false))
                    {
                        <div class="alert alert-warning">
                            <h5>
                                <i class="fa fa-warning"></i>
                                موجودی کالای @item.Name در انبار کمتر از تعداد درخواستی است.
                            </h5>
                        </div>
                    }
                    <div class="page-content-wrapper">
                        <form action="#">
                            <div class="cart-table table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th class="pro-thumbnail">تصویر</th>
                                        <th class="pro-title">نام کالا</th>
                                        <th class="pro-price">قیمت واحد</th>
                                        <th class="pro-quantity">تعداد</th>
                                        <th class="pro-subtotal">قیمت کل</th>
                                        <th class="pro-remove">حذف کردن</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @if (Model.CartItems.Any())
                                    {
                                        @foreach (var item in Model.CartItems)
                                        {
                                            <tr>
                                                <td class="pro-thumbnail">
                                                    <a asp-page="/Product" asp-route-id="@item.Slug">
                                                        <img src="~/UploadedFiles/@item.Picture" class="img-fluid" alt="@item.Name">
                                                    </a>
                                                </td>
                                                <td class="pro-title">
                                                    <a asp-page="/Product" asp-route-id="@item.Slug">@item.Name</a>
                                                </td>
                                                <td class="pro-price">
                                                    <span>@item.Price</span>
                                                </td>
                                                <td class="pro-quantity">
                                                    <div class="quantity-selection">
                                                        <input asp-for="@item.Count" type="number" min="1" onchange="changeCartItemCount('@item.Id', 'totalPrice_@item.Id', this.value)">
                                                    </div>
                                                </td>
                                                <td class="pro-subtotal">
                                                    <span id="totalPrice_@item.Id">@item.TotalPrice</span>
                                                </td>
                                                <td class="pro-remove">
                                                    <a asp-page-handler="RemoveCartItem" asp-route-id="@item.Id">
                                                        <i class="fa fa-trash-o"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                        }
                                    }


                                    </tbody>
                                </table>
                            </div>
                        </form>

                        <div class="row">
                            <div class="col-lg-6 col-12 d-flex">
                                <div class="cart-summary">
                                    <div class="cart-summary-button">
                                        <a asp-page-handler="GoToCheckout" class="checkout-btn">پرداخت</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>