ServiceHost/Areas/Admin/Pages/Accounts/Account/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Application;
using AccountManagement.Application.Contracts.Account;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Admin.Pages.Accounts.Account
{
    public class IndexModel : PageModel
    {
        private readonly IAccountApplication _accountApplication;
        private readonly IRoleApplication _roleApplication;

        public IndexModel(IAccountApplication accountApplication, IRoleApplication roleApplication)
        {
            _accountApplication = accountApplication;
            _roleApplication = roleApplication;
        }

        public List<AccountViewModel> Accounts;
        public AccountSearchModel SearchModel;
        public SelectList Roles;

        public void OnGet(AccountSearchModel searchModel)
        {
            Accounts = _accountApplication.Search(searchModel);
            Roles=new SelectList(_roleApplication.GetRoles(),"Id","Name");
        }

        public IActionResult OnGetEdit(long id)
        {
            var editAccount = _accountApplication.GetDetails(id);
            editAccount.Roles = _roleApplication.GetRoles();
            return Partial("Edit", editAccount);
        }

        public IActionResult OnGetCreate(long id)
        {
            var createAccount=new CreateAccount();
            createAccount.Roles = _roleApplication.GetRoles();
            return Partial("Create",createAccount);
        }

        public IActionResult OnPostEdit(EditAccount command)
        {
            var result = new OperationResult();
            if (ModelState.IsValid)
            {
                result=_accountApplication.Edit(command);
            }
            return new JsonResult(result);
        }

        public IActionResult OnPostCreate(CreateAccount command)
        {
            var result = new OperationResult();
            if (ModelState.IsValid)
            {
                result = _accountApplication.Register(command);
            }
            return new JsonResult(result);
        }

        public IActionResult OnGetChangePassword(long id)
        {
            var changePassword = new ChangePassword(){Id = id};
            return Partial("ChangePassword", changePassword);
        }

        public IActionResult OnPostChangePassword(ChangePassword command)
        {
            var result = new OperationResult();
            if (ModelState.IsValid)
            {
                result = _accountApplication.ChangePassword(command);
            }
            return new JsonResult(result);
        }

    }
}

ServiceHost/Areas/Admin/Pages/Accounts/Role/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Admin.Pages.Accounts.Role
{
    public class CreateModel : PageModel
    {
        private readonly IRoleApplication _roleApplication;

        public CreateModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public CreateRole Command;

        public void OnGet()
        {
            Command=new CreateRole();
        }

        public IActionResult OnPost(CreateRole command)
        {
            _roleApplication.Create(command);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Admin/Pages/Accounts/Role/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Admin.Pages.Accounts.Role
{
    public class EditModel : PageModel
    {
        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _permissionExposer;

        public EditModel(IRoleApplication roleApplication, IEnumerable<IPermissionExposer> permissionExposer)
        {
            _roleApplication = roleApplication;
            _permissionExposer = permissionExposer;
        }

        [BindProperty]
        public EditRole Role { get; set; }

        public List<SelectListItem> Permissions;

        public void OnGet(long id)
        {
            Role = _roleApplication.GetDetails(id);
            Permissions=new List<SelectListItem>();

            foreach (var exposer in _permissionExposer)
            {
                var exposedPermission = exposer.Expose();
                foreach (var (key, value) in exposedPermission)
                {
                    var group = new SelectListGroup()
                    {
                        Name = key
                    };
                    foreach (var permission in value)
                    {
                        var item = new SelectListItem(permission.Name, permission.Code.ToString())
                        {
                            Group = group
                        };

                        if (Role.MappedPermissions.Any(x => x.Code == permission.Code))
                        {
                            item.Selected = true;
                        }

                        Permissions.Add(item);
                    }
                }
            }
        }

        public IActionResult OnPost(/*EditRole command*/)
        {
            _roleApplication.Edit(Role);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Admin/Pages/Accounts/Role/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Application;
using AccountManagement.Application.Contracts.Account;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Admin.Pages.Accounts.Role
{
    public class IndexModel : PageModel
    {
        private readonly IRoleApplication _roleApplication;

        public IndexModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public List<RoleViewModel> Roles;
        public void OnGet()
        {
            Roles = _roleApplication.GetRoles();
        }

        public IActionResult OnGetEdit(long id)
        {
            var editAccount = _roleApplication.GetDetails(id);
            return Partial("Edit", editAccount);
        }

        public IActionResult OnGetCreate(long id)
        {
            var createRole = new CreateRole();
            return Partial("Create", createRole);
        }

        public IActionResult OnPostEdit(EditRole command)
        {
            var result = new OperationResult();
            if (ModelState.IsValid)
            {
                result = _roleApplication.Edit(command);
            }
            return new JsonResult(result);
        }

        public IActionResult OnPostCreate(CreateRole command)
        {
            var result = new OperationResult();
            if (ModelState.IsValid)
            {
                result = _roleApplication.Create(command);
            }
            return new JsonResult(result);
        }
    }
}

ServiceHost/Pages/Account.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Application;
using AccountManagement.Application.Contracts.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class AccountModel : PageModel
    {
        private readonly IAccountApplication _accountApplication;

        public AccountModel(IAccountApplication accountApplication)
        {
            _accountApplication = accountApplication;
        }


        [TempData]
        public string LoginMessage { get; set; }

        [TempData]
        public string RegisterMessage { get; set; }

        [BindProperty]
        public LoginModel LoginModel { get; set; }

        [BindProperty]
        public RegisterAccount RegisterAccount { get; set; }

        public void OnGet()
        {
            LoginModel = new LoginModel();
        }

        public IActionResult OnPostLogin()
        {
            var operationResult = new OperationResult();

            operationResult = _accountApplication.Login(LoginModel);
            if (operationResult.IsSucceeded)
            {
                return RedirectToPage("./Index");
            }

            LoginMessage = operationResult.Message;

            return Page();
        }

        public IActionResult OnPostRegister()
        {
            var operationResult = new OperationResult();

            var createAccount = new CreateAccount()
            {
                Username = RegisterAccount.Username,
                Password = RegisterAccount.Password,
                RoleId = 2,
                Mobile = RegisterAccount.Mobile,
                Fullname = RegisterAccount.Fullname,
            };
            operationResult = _accountApplication.Register(createAccount);
            if (!operationResult.IsSucceeded)
                RegisterMessage = operationResult.Message;


            return Page();
        }

        public IActionResult OnGetLogout()
        {
            _accountApplication.Logout();
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Admin/Pages/Accounts/Account/ChangePassword.cshtml
@model AccountManagement.Application.Contracts.Account.ChangePassword

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">تغییر کلمه عبور</h4>
</div>

<form asp-page="./Index" asp-page-handler="ChangePassword"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <input type="hidden" asp-for="Id" />
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Password" class="control-label">کلمه عبور جدید</label>
                    <input class="form-control" asp-for="Password" />
                    <span asp-validation-for="Password" class="error"></span>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="RePassword" class="control-label">تکرار کلمه عبور</label>
                    <input class="form-control" asp-for="RePassword" />
                    <span asp-validation-for="RePassword" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

ServiceHost/Areas/Admin/Pages/Accounts/Account/Create.cshtml
@model AccountManagement.Application.Contracts.Account.CreateAccount
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ایجاد کاربر جدید</h4>
</div>

<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">

            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Username" class="control-label">نام کاربری</label>
                    <input type="text" class="form-control" asp-for="Username">
                    <span asp-validation-for="Username" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Password" class="control-label">کلمه عبور</label>
                    <input type="password" class="form-control" asp-for="Password">
                    <span asp-validation-for="Password" class="error"></span>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="RoleId" class="control-label">نقش</label>
                    <select asp-for="RoleId" class="form-control" asp-items='new SelectList(Model.Roles, "Id", "Name")'>
                    </select>
                    <span asp-validation-for="RoleId" class="error"></span>
                </div>
            </div>

        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="ProfilePhoto" class="control-label">تصویر پروفایل</label>
                    <input type="file" class="form-control" asp-for="ProfilePhoto" accept="image/*">
                    <span asp-validation-for="ProfilePhoto" class="error"></span>
                </div>
            </div>

        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Fullname" class="control-label">نام</label>
                    <input type="text" class="form-control" asp-for="Fullname">
                    <span asp-validation-for="Fullname" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Mobile" class="control-label">موبایل</label>
                    <input type="text" class="form-control" asp-for="Mobile">
                    <span asp-validation-for="Mobile" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

ServiceHost/Areas/Admin/Pages/Accounts/Account/Edit.cshtml
@model AccountManagement.Application.Contracts.Account.EditAccount
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش کاربر</h4>
</div>

<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <input type="hidden" asp-for="Id"/>
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Username" class="control-label">نام کاربری</label>
                    <input type="text" class="form-control" asp-for="Username">
                    <span asp-validation-for="Username" class="error"></span>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="RoleId" class="control-label">نقش</label>
                    <select asp-for="RoleId" class="form-control" asp-items='new SelectList(Model.Roles, "Id", "Name")'>
                    </select>
                    <span asp-validation-for="RoleId" class="error"></span>
                </div>
            </div>

        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="ProfilePhoto" class="control-label">تصویر پروفایل</label>
                    <input type="file" class="form-control" asp-for="ProfilePhoto" accept="image/*">
                    <span asp-validation-for="ProfilePhoto" class="error"></span>
                </div>
            </div>

        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Fullname" class="control-label">نام</label>
                    <input type="text" class="form-control" asp-for="Fullname">
                    <span asp-validation-for="Fullname" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Mobile" class="control-label">موبایل</label>
                    <input type="text" class="form-control" asp-for="Mobile">
                    <span asp-validation-for="Mobile" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

ServiceHost/Areas/Admin/Pages/Accounts/Account/Index.cshtml
@page
@model ServiceHost.Areas.Admin.Pages.Accounts.Account.IndexModel
@{
    ViewData["title"] = "مدیریت کاربران";
}


<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./Index", "Create")">ایجاد کاربر جدید</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در کاربران</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.RoleId"></label>
                        <select asp-for="SearchModel.RoleId" asp-items="Model.Roles" class="form-control">
                            <option value="0">لطفا یک نقش را انتخاب کنید</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Mobile"></label>
                        <input class="form-control" asp-for="SearchModel.Mobile" placeholder="موبایل">
                    </div>

                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Username"></label>
                        <input class="form-control" asp-for="SearchModel.Username" placeholder="نام کاربری">
                    </div>
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Fullname"></label>
                        <input class="form-control" asp-for="SearchModel.Fullname" placeholder="نام کاربری">
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست کاربران</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>نام</th>
                                    <th>تصویر</th>
                                    <th>نام کاربری</th>
                                    <th>نقش</th>
                                    <th>تاریخ عضویت</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Accounts)
                                {
                                    <tr>
                                        <td>@item.Fullname</td>
                                        <td class="text-center">
                                            <img src="~/UploadedFiles/@item.ProfilePhoto" style="width: 70px; height: 70px" />
                                        </td>
                                        <td>@item.Username</td>
                                        <td>@item.Role</td>
                                        <td>@item.RegisteredDate</td>
                                        <td>
                                            <a class="btn btn-warning waves-effect waves-light m-b-5 pull-right m-rl-5"
                                               href="#showmodal=@Url.Page("./Index", "Edit", new { id = item.Id})">
                                                <i class="fa fa-edit"></i> ویرایش
                                            </a>

                                            <a class="btn btn-primary waves-effect waves-light m-b-5 pull-right m-rl-5"
                                               href="#showmodal=@Url.Page("./Index", "ChangePassword", new { id = item.Id})">
                                                <i class="fa fa-key"></i> تغییر کلمه عبور
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
    <script src="~/AdminTheme/assets/datatables/datatables.js"></script>
    <script src="~/AdminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/AdminTheme/assets/datatables/dataTables.bootstrap.js"></script>


    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable({
                columnDefs: [{
                    "defaultContent": "-",
                    "targets": "_all"
                }]
            });
        });
    </script>
}