ServiceHost/Areas/Admin/Pages/Accounts/Role/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Admin.Pages.Accounts.Role
{
    public class CreateModel : PageModel
    {
        private readonly IRoleApplication _roleApplication;

        public CreateModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public CreateRole Command;

        public void OnGet()
        {
            Command=new CreateRole();
        }

        public IActionResult OnPost(CreateRole command)
        {
            _roleApplication.Create(command);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Admin/Pages/Accounts/Role/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Admin.Pages.Accounts.Role
{
    public class EditModel : PageModel
    {
        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _permissionExposer;

        public EditModel(IRoleApplication roleApplication, IEnumerable<IPermissionExposer> permissionExposer)
        {
            _roleApplication = roleApplication;
            _permissionExposer = permissionExposer;
        }

        [BindProperty]
        public EditRole Role { get; set; }

        public List<SelectListItem> Permissions;

        public void OnGet(long id)
        {
            Role = _roleApplication.GetDetails(id);
            Permissions=new List<SelectListItem>();

            foreach (var exposer in _permissionExposer)
            {
                var exposedPermission = exposer.Expose();
                foreach (var (key, value) in exposedPermission)
                {
                    var group = new SelectListGroup()
                    {
                        Name = key
                    };
                    foreach (var permission in value)
                    {
                        var item = new SelectListItem(permission.Name, permission.Code.ToString())
                        {
                            Group = group
                        };

                        if (Role.MappedPermissions.Any(x => x.Code == permission.Code))
                        {
                            item.Selected = true;
                        }

                        Permissions.Add(item);
                    }
                }
            }
        }

        public IActionResult OnPost(/*EditRole command*/)
        {
            _roleApplication.Edit(Role);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Admin/Pages/Shop/Comment/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Comment;
using ShopManagement.Application.Contracts.ProductAgg;
using ShopManagement.Configuration.Permissions;

namespace ServiceHost.Areas.Admin.Pages.Shop.Comment
{
    public class IndexModel : PageModel
    {
        private readonly ICommentApplication _commentApplication;
        private readonly IProductApplication _productApplication;

        public IndexModel(ICommentApplication commentApplication,IProductApplication productApplication)
        {
            _commentApplication = commentApplication;
            _productApplication = productApplication;
        }

        public List<CommentViewModel> Comments;
        public CommentSearchModel SearchModel;
        public SelectList Products;

        [NeedsPermission(ShopPermissions.ListComments)]
        public void OnGet(CommentSearchModel searchModel)
        {
            Comments = _commentApplication.Search(searchModel);
            Products=new SelectList(_productApplication.GetProducts(),"Id","Name");
        }

        [NeedsPermission(ShopPermissions.CancelComment)]
        public IActionResult OnGetCancel(long id)
        {
            var operationResult = _commentApplication.Cancel(id);
            return RedirectToPage("Index");
        }

        [NeedsPermission(ShopPermissions.ConfirmComment)]
        public IActionResult OnGetConfirm(long id)
        {
            var operationResult = _commentApplication.Confirm(id);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Admin/Pages/Shop/Product/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Application;
using _0_Framework.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.ProductAgg;
using ShopManagement.Application.Contracts.ProductCategory;
using ShopManagement.Configuration.Permissions;

namespace ServiceHost.Areas.Admin.Pages.Shop.Product
{
    public class IndexModel : PageModel
    {
        private readonly IProductApplication _productApplication;
        private readonly IProductCategoryApplication _productCategoryApplication;

        public IndexModel(IProductApplication productApplication, IProductCategoryApplication productCategoryApplication)
        {
            _productApplication = productApplication;
            _productCategoryApplication = productCategoryApplication;
        }

        public List<ProductViewModel> Products;
        public ProductSearchModel SearchModel;
        public SelectList Categories;

        [NeedsPermission(ShopPermissions.ListProducts)]
        public void OnGet(ProductSearchModel searchModel)
        {
            Products = _productApplication.Search(searchModel);
            Categories=new SelectList(_productCategoryApplication.GetCategories(),"Id","Name");
        }

        [NeedsPermission(ShopPermissions.EditProduct)]
        public IActionResult OnGetEdit(long id)
        {
            var product = _productApplication.GetDetails(id);
            product.Categories = _productCategoryApplication.GetCategories();
            return Partial("Edit", product);
        }

        [NeedsPermission(ShopPermissions.EditProduct)]
        public IActionResult OnPostEdit(EditProduct command)
        {
            var result = new OperationResult();
            if (ModelState.IsValid)
            {
                result = _productApplication.Edit(command);
            }
            return new JsonResult(result);
        }

        [NeedsPermission(ShopPermissions.CreateProduct)]
        public IActionResult OnGetCreate()
        {
            var product = new CreateProduct();
            product.Categories = _productCategoryApplication.GetCategories();
            return Partial("Create",product );
        }

        [NeedsPermission(ShopPermissions.CreateProduct)]
        public IActionResult OnPostCreate(CreateProduct command)
        {
            var result = new OperationResult();
            if (ModelState.IsValid)
            {
                result = _productApplication.Create(command);
            }
            return new JsonResult(result);
        }

    }
}

ServiceHost/Areas/Admin/Pages/Shop/ProductCategory/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Application;
using _0_Framework.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.ProductCategory;
using ShopManagement.Configuration.Permissions;

namespace ServiceHost.Areas.Admin.Pages.Shop.ProductCategory
{
    public class IndexModel : PageModel
    {
        private readonly IProductCategoryApplication _productCategoryApplication;

        public IndexModel(IProductCategoryApplication productCategoryApplication)
        {
            _productCategoryApplication = productCategoryApplication;
        }


        public ProductCategorySearchModel SearchModel;

        public List<ProductCategoryViewModel> ProductCategories { get; set; }

        [NeedsPermission(ShopPermissions.ListProductCategories)]
        public void OnGet(ProductCategorySearchModel searchModel)
        {
            ProductCategories = _productCategoryApplication.Search(searchModel);
        }

        [NeedsPermission(ShopPermissions.CreateProductCategory)]
        public IActionResult OnGetCreate()
        {
            return Partial("Create", new CreateProductCategory());
        }

        [NeedsPermission(ShopPermissions.CreateProductCategory)]
        public IActionResult OnPostCreate(CreateProductCategory command)
        {
            var result = new OperationResult();
            if (ModelState.IsValid)
            {
                result=_productCategoryApplication.Create(command);
            }
            return new JsonResult(result);
        }

        [NeedsPermission(ShopPermissions.EditProductCategory)]
        public IActionResult OnGetEdit(long id)
        {
            return Partial("Edit", _productCategoryApplication.GetDetails(id));
        }

        [NeedsPermission(ShopPermissions.EditProductCategory)]
        public IActionResult OnPostEdit(EditProductCategory command)
        {
            var result=new OperationResult();
            if (ModelState.IsValid)
            {
                result = _productCategoryApplication.Edit(command);
            }
            return new JsonResult(result);
        }
    }
}

ServiceHost/Areas/Admin/Pages/Shop/ProductPicture/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Application;
using _0_Framework.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.ProductAgg;
using ShopManagement.Application.Contracts.ProductPicture;
using ShopManagement.Configuration.Permissions;

namespace ServiceHost.Areas.Admin.Pages.Shop.ProductPicture
{
    public class IndexModel : PageModel
    {
        private readonly IProductPictureApplication _productPictureApplication;
        private readonly IProductApplication _productApplication;

        public IndexModel(IProductPictureApplication productPictureApplication, IProductApplication productApplication)
        {
            _productPictureApplication = productPictureApplication;
            _productApplication = productApplication;
        }

        public List<ProductPictureViewModel> ProductPictures;
        public ProductPictureSearchModel SearchModel;
        public SelectList Products;

        [NeedsPermission(ShopPermissions.ListProductPictures)]
        public void OnGet(ProductPictureSearchModel searchModel)
        {
            ProductPictures = _productPictureApplication.Search(searchModel);
            Products =new SelectList(_productApplication.GetProducts(),"Id","Name");
        }

        [NeedsPermission(ShopPermissions.CreateProductPicture)]
        public IActionResult OnGetCreate()
        {
            var productPicture=new CreateProductPicture();
            productPicture.Products = _productApplication.GetProducts();
            return Partial("Create", productPicture);
        }

        [NeedsPermission(ShopPermissions.CreateProductPicture)]
        public IActionResult OnPostCreate(CreateProductPicture command)
        {
            var operationResult = new OperationResult();
            if (ModelState.IsValid)
            {
                operationResult = _productPictureApplication.Create(command);
            }
            return new JsonResult(operationResult);
        }
        [NeedsPermission(ShopPermissions.EditProductPicture)]
        public IActionResult OnGetEdit(long id)
        {
            var productPicture = _productPictureApplication.GetDetails(id);
            productPicture.Products = _productApplication.GetProducts();
            return Partial("Edit", productPicture);
        }

        [NeedsPermission(ShopPermissions.EditProductPicture)]
        public IActionResult OnPostEdit(EditProductPicture command)
        {
            var operationResult = new OperationResult();
            if (ModelState.IsValid)
            {
                operationResult= _productPictureApplication.Edit(command);
            }
            return new JsonResult(operationResult);
        }

        [NeedsPermission(ShopPermissions.RestoreProductPicture)]
        public IActionResult OnGetRemove(long id)
        {
            _productPictureApplication.Remove(id);
            return RedirectToPage("Index");
        }

        [NeedsPermission(ShopPermissions.RestoreProductPicture)]
        public IActionResult OnGetRestore(long id)
        {
            _productPictureApplication.Restore(id);
            return RedirectToPage("Index");
        }

    }
}

ServiceHost/Areas/Admin/Pages/Shop/Slide/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Application;
using _0_Framework.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.Slide;
using ShopManagement.Configuration.Permissions;


namespace ServiceHost.Areas.Admin.Pages.Shop.Slide
{
    public class IndexModel : PageModel
    {
        private readonly ISlideApplication _slideApplication;

        public IndexModel(ISlideApplication slideApplication)
        {
            _slideApplication = slideApplication;
        }

        public List<SlideViewModel> Slides;

        [NeedsPermission(ShopPermissions.ListSlides)]
        public void OnGet()
        {
            Slides = _slideApplication.Search();
        }

        [NeedsPermission(ShopPermissions.CreateSlide)]
        public IActionResult OnGetCreate()
        {
            return Partial("Create", new CreateSlide());
        }

        [NeedsPermission(ShopPermissions.CreateSlide)]
        public IActionResult OnPostCreate(CreateSlide command)
        {
            var operationResult=new OperationResult();
            if (ModelState.IsValid)
            {
                operationResult = _slideApplication.Create(command);
                
            }
            return new JsonResult(operationResult);

        }
        [NeedsPermission(ShopPermissions.EditSlide)]
        public IActionResult OnGetEdit(long id)
        {
            var editSlide = _slideApplication.GetDetails(id);
            return Partial("Edit", editSlide);
        }

        [NeedsPermission(ShopPermissions.EditSlide)]
        public IActionResult OnPostEdit(EditSlide command)
        {
            var operationResult=new OperationResult();
            if (ModelState.IsValid)
            {
                operationResult = _slideApplication.Edit(command);
            }
            return new JsonResult(operationResult);

        }
        [NeedsPermission(ShopPermissions.RemoveSlide)]
        public IActionResult OnGetRemove(long id)
        {
            var operationResult = _slideApplication.Remove(id);
            return RedirectToPage("Index");
        }
        [NeedsPermission(ShopPermissions.RestoreSlide)]
        public IActionResult OnGetRestore(long id)
        {
            var operationResult = _slideApplication.Restore(id);
            return RedirectToPage("Index");
        }

    }
}

ServiceHost/Areas/Admin/Pages/Shop/Slide/Create.cshtml
@model ShopManagement.Application.Contracts.Slide.CreateSlide

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ایجاد اسلاید جدید</h4>
</div>

<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Picture" class="control-label">تصویر</label>
                    <input type="file" class="form-control" asp-for="Picture" accept="image/*" />
                    <span asp-validation-for="Picture" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Heading" class="control-label">هدینگ</label>
                    <input class="form-control" asp-for="Heading">
                    <span asp-validation-for="Heading" class="error"></span>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Title" class="control-label">عنوان</label>
                    <input class="form-control" asp-for="Title">
                    <span asp-validation-for="Title" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Text" class="control-label">متن</label>
                    <input class="form-control" asp-for="Text">
                    <span asp-validation-for="Text" class="error"></span>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="BtnText" class="control-label">متن دکمه</label>
                    <input class="form-control" asp-for="BtnText">
                    <span asp-validation-for="BtnText" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureTitle" class="control-label">عنوان</label>
                    <input class="form-control" asp-for="PictureTitle">
                    <span asp-validation-for="PictureTitle" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureAlt" class="control-label">Alt</label>
                    <input class="form-control" asp-for="PictureAlt">
                    <span asp-validation-for="PictureAlt" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Link" class="control-label">لینک</label>
                    <input class="form-control" asp-for="Link">
                    <span asp-validation-for="Link" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

ServiceHost/Areas/Admin/Pages/Shop/Slide/Edit.cshtml
@model ShopManagement.Application.Contracts.Slide.EditSlide

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش اسلاید @Model.Picture</h4>
</div>

<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <input type="hidden" asp-for="Id" />
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Picture" class="control-label">تصویر</label>
                    <input type="file" class="form-control" asp-for="Picture" accept="image/*" />
                    <span asp-validation-for="Picture" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Heading" class="control-label">هدینگ</label>
                    <input class="form-control" asp-for="Heading">
                    <span asp-validation-for="Heading" class="error"></span>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Title" class="control-label">عنوان</label>
                    <input class="form-control" asp-for="Title">
                    <span asp-validation-for="Title" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Text" class="control-label">متن</label>
                    <input class="form-control" asp-for="Text">
                    <span asp-validation-for="Text" class="error"></span>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="BtnText" class="control-label">متن دکمه</label>
                    <input class="form-control" asp-for="BtnText">
                    <span asp-validation-for="BtnText" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureTitle" class="control-label">عنوان</label>
                    <input class="form-control" asp-for="PictureTitle">
                    <span asp-validation-for="PictureTitle" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureAlt" class="control-label">Alt</label>
                    <input class="form-control" asp-for="PictureAlt">
                    <span asp-validation-for="PictureAlt" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Link" class="control-label">لینک</label>
                    <input class="form-control" asp-for="Link">
                    <span asp-validation-for="Link" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

ServiceHost/Areas/Admin/Pages/Shop/Slide/Index.cshtml
@page
@using ShopManagement.Configuration.Permissions
@model ServiceHost.Areas.Admin.Pages.Shop.Slide.IndexModel
@{
    ViewData["title"] = "مدیریت اسلایدها";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a permission="@ShopPermissions.CreateSlide" class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./Index", "Create")">ایجاد اسلاید جدید</a>
        </p>
    </div>
</div>

@*<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در گروه تصاویر</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.ProductId"></label>
                        <select class="form-control" asp-for="SearchModel.ProductId" asp-items='Model.Products'></select>
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>*@

<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست اسلایدها</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>تصویر</th>
                                    <th>هدینگ</th>
                                    <th>عنوان</th>
                                    <th>لینک</th>
                                    <th>وضعیت</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Slides)
                                {
                                    <tr>
                                        <td>
                                            <img src="~/UploadedFiles/@item.Picture" style="width: 70px; height: 70px" />
                                        </td>
                                        <td>@item.Heading</td>
                                        <td>@item.Title</td>
                                        <td>@item.Link</td>
                                        <td class="text-center">
                                            @if (item.IsRemoved==true)
                                            {
                                                <i class="fa fa-remove fa-2x text-danger"></i>
                                            }
                                            else
                                            {
                                                <i class="fa fa-check fa-2x text-success"></i>
                                            }
                                        </td>
                                        <td>
                                            <a  permission="@ShopPermissions.EditSlide" class="btn btn-warning waves-effect waves-light m-b-5 pull-right m-rl-5"
                                               href="#showmodal=@Url.Page("./Index", "Edit", new { id = item.Id})">
                                                <i class="fa fa-edit"></i> ویرایش
                                            </a>
                                            @if (item.IsRemoved==true)
                                            {
                                                <a permission="@ShopPermissions.RestoreSlide" class="btn btn-success waves-effect waves-light m-b-5" asp-page-handler="Restore" asp-route-id="@item.Id">فعالسازی</a>
                                            }
                                            else
                                            {
                                                <a permission="@ShopPermissions.RemoveSlide" class="btn btn-danger waves-effect waves-light m-b-5" asp-page-handler="Remove"
                                                   asp-route-id="@item.Id">
                                                    غیر فعالسازی
                                                </a>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
    <script src="~/AdminTheme/assets/datatables/datatables.js"></script>
    <script src="~/AdminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/AdminTheme/assets/datatables/dataTables.bootstrap.js"></script>


    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable({
                columnDefs: [{
                    "defaultContent": "-",
                    "targets": "_all"
                }]
            });
        });
    </script>
}