ServiceHost/Areas/Admin/Pages/Accounts/Role/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Admin.Pages.Accounts.Role
{
    public class CreateModel : PageModel
    {
        private readonly IRoleApplication _roleApplication;

        public CreateModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public CreateRole Command;

        public void OnGet()
        {
            Command=new CreateRole();
        }

        public IActionResult OnPost(CreateRole command)
        {
            _roleApplication.Create(command);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Admin/Pages/Accounts/Role/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Admin.Pages.Accounts.Role
{
    public class EditModel : PageModel
    {
        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _permissionExposer;

        public EditModel(IRoleApplication roleApplication, IEnumerable<IPermissionExposer> permissionExposer)
        {
            _roleApplication = roleApplication;
            _permissionExposer = permissionExposer;
        }

        [BindProperty]
        public EditRole Role { get; set; }

        public List<SelectListItem> Permissions;

        public void OnGet(long id)
        {
            Role = _roleApplication.GetDetails(id);
            Permissions=new List<SelectListItem>();

            foreach (var exposer in _permissionExposer)
            {
                var exposedPermission = exposer.Expose();
                foreach (var (key, value) in exposedPermission)
                {
                    var group = new SelectListGroup()
                    {
                        Name = key
                    };
                    foreach (var permission in value)
                    {
                        var item = new SelectListItem(permission.Name, permission.Code.ToString())
                        {
                            Group = group
                        };

                        if (Role.MappedPermissions.Any(x => x.Code == permission.Code))
                        {
                            item.Selected = true;
                        }

                        Permissions.Add(item);
                    }
                }
            }
        }

        public IActionResult OnPost(/*EditRole command*/)
        {
            _roleApplication.Edit(Role);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Admin/Pages/Inventory/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Application;
using _0_Framework.Infrastructure;
using InventoryManagement.Application.Contracts.Inventory;
using InventoryManagement.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.ProductAgg;

namespace ServiceHost.Areas.Admin.Pages.Inventory
{
    public class IndexModel : PageModel
    {
        private readonly IInventoryApplication _inventoryApplication;
        private readonly IProductApplication _productApplication;

        public IndexModel(IInventoryApplication inventoryApplication, IProductApplication productApplication)
        {
            _inventoryApplication = inventoryApplication;
            _productApplication = productApplication;
        }

        public SelectList Products;
        public InventorySearchModel SearchModel;
        public List<InventoryViewModel> Inventory;

        [NeedsPermission(InventoryPermissions.ListInventory)]
        public void OnGet(InventorySearchModel searchModel)
        {
            Products=new SelectList(_productApplication.GetProducts(),"Id","Name");
            Inventory = _inventoryApplication.Search(searchModel);
        }

        [NeedsPermission(InventoryPermissions.EditInventory)]
        public IActionResult OnGetEdit(long id)
        {
            var inventory = _inventoryApplication.GetDetails(id);
            inventory.Products = _productApplication.GetProducts();
            return Partial("Edit", inventory);
        }

        [NeedsPermission(InventoryPermissions.CreateInventory)]
        public IActionResult OnGetCreate()
        {
            var inventory = new CreateInventory();
            inventory.Products = _productApplication.GetProducts();
            return Partial("Create", inventory);
        }

        [NeedsPermission(InventoryPermissions.CreateInventory)]
        public IActionResult OnPostCreate(CreateInventory command)
        {
            var operationResult = new OperationResult();
            if (ModelState.IsValid)
            {
                operationResult=_inventoryApplication.Create(command);
            }

            return new JsonResult(operationResult);
        }

        [NeedsPermission(InventoryPermissions.EditInventory)]
        public IActionResult OnPostEdit(EditInventory command)
        {
            var operationResult = new OperationResult();
            if (ModelState.IsValid)
            {
                operationResult = _inventoryApplication.Edit(command);
            }

            return new JsonResult(operationResult);
        }

        [NeedsPermission(InventoryPermissions.Increase)]
        public IActionResult OnGetIncrement(long id)
        {
            var increaseInventory = new IncreaseInventory()
            {
                InventoryId = id
            };
            return Partial("Increment",increaseInventory);
        }
        [NeedsPermission(InventoryPermissions.Reduce)]
        public IActionResult OnGetDecrement(long id)
        {
            var decreaseInventory = new DecreaseInventory()
            {
                InventoryId = id
            };
            return Partial("Decrement", decreaseInventory);
        }
        [NeedsPermission(InventoryPermissions.Increase)]
        public IActionResult OnPostIncrement(IncreaseInventory command)
        {
            var operationResult = new OperationResult();
            if (ModelState.IsValid)
            {
                operationResult=_inventoryApplication.Increase(command);
            }
            return new JsonResult(operationResult);
        }
        [NeedsPermission(InventoryPermissions.Reduce)]
        public IActionResult OnPostDecrement(DecreaseInventory command)
        {
            var operationResult = new OperationResult();
            if (ModelState.IsValid)
            {
                operationResult = _inventoryApplication.Decrease(command);
            }
            return new JsonResult(operationResult);
        }

        [NeedsPermission(InventoryPermissions.OperationLog)]
        public IActionResult OnGetOperations(long id)
        {
            var operations = _inventoryApplication.GetOperations(id);
            return Partial("Operations",operations);
        }
    }
}

ServiceHost/Areas/Admin/Pages/Inventory/Create.cshtml
@model InventoryManagement.Application.Contracts.Inventory.CreateInventory

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ایجاد محصول جدید در انبار</h4>
</div>

<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="ProductId" class="control-label">محصول</label>
                    <select asp-for="ProductId" asp-items='new SelectList(Model.Products,"Id","Name")' class="form-control selectProduct"></select>
                    <span asp-validation-for="ProductId" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="UnitPrice" class="control-label">قیمت</label>
                    <input class="form-control" asp-for="UnitPrice">
                    <span asp-validation-for="UnitPrice" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

ServiceHost/Areas/Admin/Pages/Inventory/Decrement.cshtml
@model InventoryManagement.Application.Contracts.Inventory.DecreaseInventory

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">افزایش موجودی</h4>
</div>

<form asp-page="./Index" asp-page-handler="Decrement"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <input type="hidden" asp-for="InventoryId" />
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Count" class="control-label">تعداد</label>
                    <input asp-for="Count" class="form-control"/>
                    <span asp-validation-for="Count" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group no-margin">
                    <label asp-for="Description" class="control-label">توضیحات</label>
                    <textarea class="form-control autogrow" asp-for="Description"
                              style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                    <span asp-validation-for="Description" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">کاهش موجودی</button>
    </div>
</form>

ServiceHost/Areas/Admin/Pages/Inventory/Edit.cshtml
@model InventoryManagement.Application.Contracts.Inventory.EditInventory

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش محصول در انبار</h4>
</div>

<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <input type="hidden" asp-for="Id" />
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="ProductId" class="control-label">محصول</label>
                    <select asp-for="ProductId" asp-items='new SelectList(Model.Products, "Id", "Name")' class="form-control selectProduct"></select>
                    <span asp-validation-for="ProductId" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="UnitPrice" class="control-label">قیمت</label>
                    <input class="form-control" asp-for="UnitPrice">
                    <span asp-validation-for="UnitPrice" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

ServiceHost/Areas/Admin/Pages/Inventory/Increment.cshtml
@model InventoryManagement.Application.Contracts.Inventory.IncreaseInventory

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">افزایش موجودی</h4>
</div>

<form asp-page="./Index" asp-page-handler="Increment"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <input type="hidden" asp-for="InventoryId" />
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Count" class="control-label">تعداد</label>
                    <input asp-for="Count" class="form-control"/>
                    <span asp-validation-for="Count" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group no-margin">
                    <label asp-for="Description" class="control-label">توضیحات</label>
                    <textarea class="form-control autogrow" asp-for="Description"
                      style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                    <span asp-validation-for="Description" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">افزایش موجودی</button>
    </div>
</form>

ServiceHost/Areas/Admin/Pages/Inventory/Index.cshtml
@page
@model ServiceHost.Areas.Admin.Pages.Inventory.IndexModel
@{
    ViewData["title"] = "انبارداری";
}


<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./Index", "Create")">ایجاد محصول جدید در انبار</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در انبار</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.ProductId"></label>
                        <select asp-for="SearchModel.ProductId" asp-items="Model.Products" class="form-control"></select>
                    </div>
                    <div class="form-group m-r-10">
                        <div class="checkbox checkbox-primary">
                            <input asp-for="SearchModel.IsNotInStock" />
                            <label asp-for="SearchModel.IsNotInStock">
                                جستجو در بین ناموجودها
                            </label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست محصولات موجود در انبار</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>نام محصول</th>
                                    <th>موجودی در انبار</th>
                                    <th>قیمت</th>
                                    <th>وضعیت</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Inventory)
                                {
                                    <tr>
                                        <td>@item.Product</td>
                                        <td class="text-center">@item.CurrentCount</td>
                                        <td>@item.UnitPrice</td>
                                        <td class="text-center">
                                            @if (item.IsInStock)
                                            {
                                                <i class="fa fa-check  fa-2x  text-success"></i>
                                            }
                                            else
                                            {
                                                <i class="fa fa-remove fa-2x text-danger"></i>
                                            }
                                        </td>
                                        <td>
                                            <a class="btn btn-warning waves-effect waves-light m-b-5 pull-right m-rl-5"
                                               href="#showmodal=@Url.Page("./Index", "Edit", new { id = item.Id})">
                                                <i class="fa fa-edit"></i> ویرایش
                                            </a>

                                            <a class="btn btn-success waves-effect waves-light m-b-5 pull-right m-rl-5"
                                               href="#showmodal=@Url.Page("./Index", "Increment", new { id = item.Id})">
                                                <i class="fa fa-plus"></i> افزایش موجودی
                                            </a>

                                            <a class="btn btn-danger waves-effect waves-light m-b-5 pull-right m-rl-5"
                                               href="#showmodal=@Url.Page("./Index", "Decrement", new { id = item.Id})">
                                                <i class="fa fa-minus"></i> کاهش موجودی
                                            </a>

                                            <a class="btn btn-primary waves-effect waves-light m-b-5 pull-right m-rl-5"
                                               href="#showmodal=@Url.Page("./Index", "Operations", new { id = item.Id})">
                                                <i class="fa fa-recycle"></i>مشاهده گردش انبار
                                            </a>


                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
    <script src="~/AdminTheme/assets/datatables/datatables.js"></script>
    <script src="~/AdminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/AdminTheme/assets/datatables/dataTables.bootstrap.js"></script>


    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable({
                columnDefs: [{
                    "defaultContent": "-",
                    "targets": "_all"
                }]
            });
        });
    </script>
}

ServiceHost/Areas/Admin/Pages/Inventory/Operations.cshtml
@model List<InventoryManagement.Application.Contracts.OperationLogViewModel>

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">سوابق انبار</h4>
</div>

<div class="modal-body">
    <table id="datatable" class="table table-bordered">
        <thead>
            <tr>
                <th>تاریخ</th>
                <th>اپراتور</th>
                <th>تعداد</th>
                <th>موجودی فعلی</th>
                <th>توضیحات</th>
            </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr class="text-white @(item.IsIncrement ? "bg-success":"bg-danger")">
                <td>@item.OperationDate</td>
                <td>@item.Operator</td>
                <td>@item.Count</td>
                <td>@item.CurrentCount</td>
                <td>@item.Description</td>
            </tr>
        }
        </tbody>
    </table>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
</div>